[package]
name = "substreams-solana-core"
version = "0.11.1"
edition = "2021"
description = "Substreams development kit for Solana chains, contains Rust Firehose Block model and helpers."
homepage = "https://substreams.streamingfast.io/"
repository = "https://github.com/streamingfast/substreams-solana/tree/develop/core"
license = "Apache-2.0"
readme = "../README.md"
keywords = ["substreams", "solana", "streamingfast", "firehose", "thegraph"]
categories = ["wasm"]
rust-version = "1.64"

[dependencies]
prost = { version = "0.11" }
prost-types = "0.11"
bs58 = "0.4.0"

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
anyhow = "1"
hex = "0.4"
paste = "1"
pretty_assertions = "1.4"
